#!/usr/bin/env bash
# Brings the stack up: mounts the data disks, refreshes secrets from Key
# Vault, starts compose. ExecStart of dpv-compose.service, so it runs on every
# boot and on every `systemctl restart dpv-compose.service`.
#
# This used to be generated by cloud-init (a heredoc in custom_data), which
# meant any change to it required rebuilding the VM. It now lives in the repo
# like the systemd units and reaches a running VM through `git pull`. The only
# value it needed from Terraform, the Key Vault name, comes from /etc/dpv/env,
# which cloud-init writes once.
set -euo pipefail

# shellcheck source=/dev/null
source /etc/dpv/env

trap 'logger -p user.err -t dpv-boot "boot.sh failed at line ${LINENO} — stack not (fully) started, see: journalctl -u dpv-compose"' ERR

/opt/dpv/scripts/mount-data-disks.sh

az login --identity --allow-no-subscriptions >/dev/null
/opt/dpv/scripts/fetch-secrets.sh "${KEY_VAULT_NAME}"

cd /opt/dpv/compose
docker compose up -d --build
